<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Contenuto',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => 'Parent ID',
    'Status' => 'Stato',
    'Level' => 'Livello',
    'Created by' => 'Creato da',
    'Updated by' => 'Modificato da',
    'Related to' => 'Related to',
    'Url' => 'Url',
    'Created date' => 'Data di creazione',
    'Updated date' => 'Data di modifica',
    'View' => 'View',
    'Update' => 'Update',
    'Delete' => 'Elimina',
    'Reply' => 'Rispondi',
    'Comments ({0})' => 'Commenti ({0})',
    'Comment cannot be blank.' => 'I commmenti non possono essere vuoti.',
    'Comment has not been deleted. Please try again!' => 'Il commento non è stato eliminato. Prova ancora',
    'Add a comment...' => 'Aggiungi un commento...',
    'Comment' => 'Commento',
    'Oops, something went wrong. Please try again later.' => 'Oops, qualcosa è andato male. Prova ancora più tardi.',
    'The requested page does not exist.' => 'La pagina richiesta non esiste.',
    'Comment has been deleted.' => 'Il commento è stato eliminato.',
    'Comment has been saved.' => 'Il commento è stato salvato.',
    'Click here to cancel reply.' => 'Clicca qui per eliminare la risposta.',
    'Comments Management' => 'Comments Management',
    'Select Status' => 'Seleziona stato',
    'Select Author' => 'Seleziona autore',
    'Update Comment: {0}' => 'Modifica Commento: {0}',
    'Active' => 'Attivo',
    'Deleted' => 'Eliminato',
    'Go Back' => 'Torna indietro',
    'Archived'=> 'Archiviato',
    'Archive'=> 'Archivia',
    'Restore'=> 'Ripristina',
    'Update' => 'Modifica',
    'Comment archiving status has changed!'=>'Lo stato di archiviazione del commento è cambiato!',
    'Comment archiving status has not changed. Please try again!' => 'Lo stato di archiviazione del commento non è cambiato, tenta ancora!',
    'Show replies ({0})'=> 'Visualizza risposte ({0})'
];

